### ISSUE TITLE
Feature Enhancement: Disable public "Launch!" link when world is offline

### ISSUE THREAD

**Issue by brianmiller** [brianmiller/phvalheim-server#10]

**Comment by brianmiller** [comment]
Maybe change color of tile borders and links to be "grayed" out.

**Comment by Maxver0** [comment]
Would it be possible to provide Online or Offline server status? or change the color of the launch link to be red when down and green when up.

**Comment by brianmiller** [comment]
Maybe a status indicator/color changing bubble.  I'd like to keep the color scheme as consistent as possible.
