### ISSUE TITLE
Feature Enhancement: Delete button security 

### ISSUE THREAD

**Issue by darkhorse7881** [brianmiller/phvalheim-server#14]
add a pop up that makes you type in the world name before deleting.

**Comment by brianmiller** [comment]
We'll add this.

**Comment by brianmiller** [comment]
Commit https://github.com/brianmiller/phvalheim-server/commit/d6563c5d701dfa42b728877de8d43e6dd139d6a1 implements admin interface confirmation dialogs when clicking "Delete" on a world and "Database Browser" buttons.
