### ISSUE TITLE
Feature Enhancement: Selection of game branch during world creation

### ISSUE THREAD

**Issue by Maxver0** [brianmiller/phvalheim-server#16]
It would be nice to have the possibility to select different branches (beta versions) of the game like "public-test" during the creation of the world. 

In order to achieve this currently, we would have to manually update the https://github.com/brianmiller/phvalheim-server/blob/master/container/games/valheim/scripts/startWorld.sh  with `-beta public-test -betapassword "yesimadebackups" `?

**Comment by brianmiller** [comment]
This is doable.

**Comment by brianmiller** [comment]
[Here's the release notes](https://github.com/brianmiller/phvalheim-server/releases/tag/2.16). 

Closing this issue as the feature now exists.  Feel free to open another issue if a bug or feature request is encountered.  Also take a look at our Discord where we have a small community of phvalheim-server admins.
