### ISSUE TITLE
listing none on citizens page dosent work

### ISSUE THREAD

**Issue by darkhorse7881** [brianmiller/phvalheim-server#26]
continues to not let anyone join

**Comment by brianmiller** [comment]
Yeah. This is expected.  

From the postings, questions and suggestions in this area, It seems folks would like a "no ACL" option--fully public. 

I'm pretty sure this is doable with a new SQL function in db_gets.php.

I'm marking this as a feature enhancement and will likely bundle related commits with other smaller changes.

**Comment by brianmiller** [comment]
E.g.,

If the theoretical "public" bit is set, ignore the Citizens ACL list, send the launch parameters to include the public option during world start and possibly allow editing of the world join password.

**Comment by brianmiller** [comment]
resolved with release of 2.20
