### ISSUE TITLE
automatically implement config files or don't delete them when updating and restarting server

### ISSUE THREAD

**Issue by Mitarius51** [brianmiller/phvalheim-server#28]
Is it possible to automatically implement config files or leave the config files untouched when restarting the valheim server?
Like write-protecting them or something?

Right now i have to manually upload the config files i have edited (valheim-plus, BetterArchery,Better_UI) manually after each update and restart of the server. If i forget that, the inventory of the char and storage is smaller and some items are lost.

**Comment by brianmiller** [comment]
The feature already exists. I need to work on the wiki/documentation.

Just copy any config files you want to make persistent to the custom_configs directory.

![Screenshot_20230125-060126_Chrome.jpg](https://user-images.githubusercontent.com/342276/214583543-7fef27f6-0706-40ba-a550-f05f33fdd801.jpg)

You can also load custom plugins and patchers that aren't in Thunderstore.

**Comment by brianmiller** [comment]
Closing
