### ISSUE TITLE
Hide World Seed from Client UI

### ISSUE THREAD

**Issue by Popschlock** [brianmiller/phvalheim-server#32]
We would like to hide the world seed from the client UI to encourage playing the game for exploration versus looking up the world online using the seed to know where bosses/etc are. Can you add a feature that allows the seed to be hidden in the client UI?

**Comment by brianmiller** [comment]
This is doable. I've been considering a settings page within the admin UI.

If we do this, it will come in multiple releases. First, I can fairly quickly add a new parameter in the frontend config file.

The admin UI changes will take more time.

I'll see what I can do to bring this into the next few releases. 


-Brian

**Comment by brianmiller** [comment]
resolved by phvalheim-server >=2.23
