### ISSUE TITLE
URI Issue and world not showing on public site

### ISSUE THREAD

**Issue by SpaceFahad** [brianmiller/phvalheim-server#43]
Unraid 6.12.3

I set up port forwarding on 25000-25003 UDP to my unraid
setup CF tunnel to the public page for logging in
setup ddns for the DNS access/IP

and when I sign in through Steam I don't see the server/world. "You don't have any worlds in your library."

 when I press the "launch" from the admin console I get the following:

`
## PhValheim Launcher 2.0.9 ##

PhValheim Remote Server: ://192.168.99.9:8681
Steam root directory was found: c:\program files (x86)\steam
PhValheim root directory was found: C:\Users\USERNAME\AppData\Roaming\PhValheim
World root directory was found: C:\Users\USERNAME\AppData\Roaming\PhValheim\worlds\192.168.99.9\tester
Valheim root directory was found: E:\\SteamLibrary\steamapps\common\Valheim
Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at PhValheim.Syncer.PhValheim.Sync(String phvalheimURL)
   at PhValheim.PhValheim.Main(String[] args)
`

connecting directly to the world through DDNS/IP I can get in server but without any mod or anything of course since the phvalheim/connection is not working as intended.

any ideas?

**Comment by RotasOpera** [comment]
Had the same issue just now. It works if you launch the page via the public url, not the local IP

**Comment by SpaceFahad** [comment]
> Had the same issue just now. It works if you launch the page via the public url, not the local IP

does the server show in the list on the public website after signing in with steam? cause for me they don't show at all. also I tried launching the page with the URL instead of the IP but I had the same issue.

**Comment by RotasOpera** [comment]
Only showed after I added my steam ID

**Comment by SpaceFahad** [comment]
Re-installing the whole Phvalheim for the second time seems to have fixed the issue for me!

**Comment by brianmiller** [comment]
Resolved with release 2.13
