### ISSUE TITLE
tsmods DB out of date, can I manually update it?

### ISSUE THREAD

**Issue by gstrange42** [brianmiller/phvalheim-server#44]
It's loading the previous versions of mods causing no end of server issues,

**Comment by gstrange42** [comment]
Ah it seems I hate to wait 12 hours after install for it to update. 

Maybe implement a manual update button, and limit it's use to once an house to stop server hammering.

**Comment by brianmiller** [comment]
Yeah, the sync runs every 12hrs.  phvalheim-server also syncs from GitHub, but we haven't enabled that feature just yet.  I'm been slammed at the office.

**Comment by brianmiller** [comment]
resolved with phvalheim-server >=2.23
