### ISSUE TITLE
Error when trying to launch phvalheim client from admin screen

### ISSUE THREAD

**Issue by wwray** [brianmiller/phvalheim-server#45]
Thanks for this awesome docker Brian, this is exactly what I was looking for to host a bunch of different worlds on the same server. One small problem. When I try and click the "Launch" button within the admin console I get the following error:

![Screenshot 2023-09-08 105118](https://github.com/brianmiller/phvalheim-server/assets/49773454/e67ada7e-5904-42b4-aeae-0f2e7cb0f182)

I tried changing the URL in the docker config to put a prefix (eg http://) and I noticed that the error message changes depending on whether I try and access it via the URL or via the IP address of the unraid server. Not a big deal because the public page launches correctly but thought I'd bring it to your attention.

Thanks.

**Comment by brianmiller** [comment]
I'm glad you're enjoying it.

I know... 🤦 

With 2.12 I caused two regressions.

- This one, where the launch string generated at the admin UI is busted.
- And issue #41 where entering a custom seed always generates a world with the default seed.

I've been busy at the office and hopefully I'll get some free time soon to fix these issues. For now the workaround is to use the launch string from the public UI. Just make sure you add your players' SteamIDs to the Citizen list.  This is what grants them access and renders the world tile on the public page.

**Comment by brianmiller** [comment]
Resolved with release 2.13
