### ISSUE TITLE
Created world, unable to launch?

### ISSUE THREAD

**Issue by SkuffedKnerd** [brianmiller/phvalheim-server#46]
Hello,
   I amusing Unraid 6.12.4 and just installed this docker. Everything seemed to go smoothly, I started the WebUI and created a new world. The Engine Mode is still on "updating" and I am unable to click on Launch or anything else to get the world started and I can't see any indication that it's doing anything for "updating".  Is this normal?

**Comment by brianmiller** [comment]
This is related to #45.  Launching from the public interface is the workaround until I get time to push the latest update.

**Comment by brianmiller** [comment]
Resolved with release 2.13
