### ISSUE TITLE
Installing Ashlands (-beta public-test)

### ISSUE THREAD

**Issue by jomaskm** [brianmiller/phvalheim-server#53]
Not really an "Issue" as such, but is there a way to install the public test of Valheim instead of latest version?

**Comment by brianmiller** [comment]
This has been asked a few times.  I will try and give this priority for the next release.

We'll need to add a database flag, toggled by the web ui, and a change to the world start commands.  It shouldn't be a problem. I just don't know when I can get to it. Unless someone wants to give it a shot and merge :).

If you want it now, you can edit ```/opt/stateless/games/valheim/scripts/startWold.sh``` from within the container.

```docker exec -it phvalheim-server /bin/bash```
```vim /opt/stateless/games/valheim/scripts/startWorld.sh```

Change: _this will affect all worlds_

this:
```
exec /opt/stateful/games/valheim/worlds/$worldName/game/valheim_server.x86_64 \
-nographics \
-batchmode \
-name $worldName \
-port $worldPort \
-world $worldName \
-oldconsole \
-public 0 \
-savedir /opt/stateful/games/valheim/worlds/$worldName/game/.config/unity3d/IronGate/Valheim
```

to this:

```
exec /opt/stateful/games/valheim/worlds/$worldName/game/valheim_server.x86_64 \
-nographics \
-batchmode \
-name $worldName \
-port $worldPort \
-world $worldName \
-oldconsole \
-public 0 \
-beta public-test \
-betapassword yesimadebackups \
-savedir /opt/stateful/games/valheim/worlds/$worldName/game/.config/unity3d/IronGate/Valheim
```

**Comment by brianmiller** [comment]
The client will need a change too. 😞

**Comment by jomaskm** [comment]
That's too bad. If it's possible to implement though, it would be extremely helpful for hosting servers for this game.

**Comment by jomaskm** [comment]
Sorry, misclick on that close. 😶

**Comment by jomaskm** [comment]
> beta / public-test has been added to phvalheim-server 2.16rc. Stand by for instructions.

Not the hero we deserved, but the hero we got. 🤩
Amazing!

**Comment by brianmiller** [comment]
[Here's the release notes](https://github.com/brianmiller/phvalheim-server/releases/tag/2.16). 

Closing this issue as the feature now exists.  Feel free to open another issue if a bug or feature request is encountered.  Also take a look at our Discord where we have a small community of phvalheim-server admins.
