### ISSUE TITLE
Could not connect to the remote PhValheim server

### ISSUE THREAD

**Issue by Sluggeru** [brianmiller/phvalheim-server#55]
## PhValheim Launcher 2.0.10 ##

PhValheim Remote Server: https://vh.noname.me
Steam root directory was found: i:\program files (x86)\steam
PhValheim root directory was found: C:\Users\xxxxxx\AppData\Roaming\PhValheim
World root directory was found: C:\Users\xxxx\AppData\Roaming\PhValheim\worlds\vh.noname.me\MadCapCom
Valheim root directory was found: I:\\Program Files (x86)\\Steam\steamapps\common\Valheim

Checking to see if local and remote world contexts match for 'MadCapCom'...

ERROR: Could not connect to the remote PhValheim server 'https://vh.noname.me'.

Press the Enter key to exit.

PhValheim Client is up-to-date.

All other Players have no problem starting the game and connecting. 
I have tried clean install of firefox browser. Checked any kind of filters. Turned off Microsoft defender. Turned off firewall. 
Tried reinstalling Valheim. no mods. Tried installing on C: drive.  
What else can I check or test?

**Comment by brianmiller** [comment]
Can you resolve your PhValheim hostname from your LAN and the Internet?  

vh.noname.me doesn't resolve, unless that is the sanitized name due to the public post.

**Comment by Sluggeru** [comment]
Yes I can resolve the server with browser. I did sanitize the name. I can send you the name privately.
![client](https://github.com/brianmiller/phvalheim-server/assets/105090114/dfcacf47-b044-4cfe-8194-05c77bd847f0)

**Comment by Sluggeru** [comment]
DM where?  I sent the link to brian@phospher.com

**Comment by brianmiller** [comment]
Generally, our Discord.  Email works too.

**Comment by brianmiller** [comment]
From the internet, your PhValheim server appears to be working correctly.  I was able to download the MadCapCom.zip payload without issue.  Can you successfully download this file from your LAN?

https://<SANITIZED>/stateful/valheim/worlds/MadCapCom/MadCapCom.zip

**Comment by brianmiller** [comment]
It looks like you're using CloudFlare.  You may need to disable caching if you're updating your worlds quickly and rapidly testing.


Here's our cache rule for https://phvalheim.com
![image](https://github.com/brianmiller/phvalheim-server/assets/342276/0924575d-f73f-4ed2-a0fc-87fa02132bfd)

**Comment by Sluggeru** [comment]
I can not download MadCapCom.zip.
This site can’t be reached
 stateful’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE

This is not my server. Are you saying the server is using CloudFlare?

**Comment by brianmiller** [comment]
Yes. The URL you sent me in an email contained a hostname that is frontended by CloudFlare.  The phvalheim-server instance appears to be working normally.

It looks like you're having local DNS issues resolving the hostname.  Can you ping the phvalheim hostname you sanitized?

**Comment by Sluggeru** [comment]
My mistake . I didn't include the sanitized server name. Yes I can download MadCapCom.zip.

**Comment by brianmiller** [comment]
You should have to do anything.  

Try deleting the entire `%appdata%\PhValheim` directory and launch the game again from the PhValheim public UI.

**Comment by Sluggeru** [comment]
Deleted  contents  of %appdata%\PhValheim directory. ran PhValheim public UI, clicked launch nothing.  Upper right corner says download PhValheim client and install. Then I see same error as message #3 above.

**Comment by brianmiller** [comment]
Oops,.. I meant the worlds dir.  No biggie.  Reinstall the phvalheim client and try to launch again.

**Comment by Sluggeru** [comment]
Tried Launching again. Same error.
\AppData\Roaming\PhValheim\phvalheim-client  contains  phvalheim-client.exe.
\AppData\Roaming\PhValheim\worlds\sanatized\MadCapCom  is empty.

I have tried disabling ad filters,  have no anti virus. Tried disabling firewall.
So what's next?

**Comment by brianmiller** [comment]
Can you join our Discord?  This requires real-time chat.

**Comment by Sluggeru** [comment]
Sure what's the discord name?

**Comment by brianmiller** [comment]
https://discord.gg/8RMMrJVQgy

**Comment by brianmiller** [comment]
Issue appears to be with hosting provider.  Closing.
