### ISSUE TITLE
OSX / Linux Client App?

### ISSUE THREAD

**Issue by sh0nuff** [brianmiller/phvalheim-server#59]
I was extremely excited to find this (I discovered it through Unraid), but then a bit dissapointed that the mandatory player client is Windows only. I have a couple friends who I play with currently and we'd find this to be the perfect tool we've been searching for, however one of our group is on Linux, and another on OSX, making this a no-go.

I wish we had more development know-how to participate creating the client for other platforms.. happy to kick a few $ towards keeping things moving forwards in this regard

**Comment by sh0nuff** [comment]
Ok, I didn't realize as the front page only specifically mentions Windows

**Comment by brianmiller** [comment]
Yeah, I'm open to a merge! :)

Give it a shot a let us know if you run into any trouble.  We have a growing community on Discord as well and folks are generally happy to help out.
