### ISSUE TITLE
Feature Enhancement: Docker Network types

### ISSUE THREAD

**Issue by brianmiller** [brianmiller/phvalheim-server#7]
So far, we've only tested Bridge mode.  We need to test L2 connectivity and update the readme for more clarity.

**Comment by spoonwzd** [comment]
> 

FYI if you set "Host access to custom networks" to enabled in unraid docker advanced options (docker has to be stopped to be able to change) the docker apps can then communicate with the unraid IP.

**Comment by brianmiller** [comment]
Yeah, this is likely needed for those hosting reverse proxies on the same Unraid host using custom networks. 

We're reassessing the internal webserver architecture and believe we can bring everything internal to the container itself.

More to come!

**Comment by brianmiller** [comment]
Solved by #17 

As of phvalheim-server >=2.0
- A reverse proxy is no longer required
- The admin interface listens on a isolated port
- The public interface no longer requires SSL/TLS
- Direct IP connections to public and admin interfaces work
