### ISSUE TITLE
Feature Enhancement: Make PhValheim work without DNS resolution (direct IP)

### ISSUE THREAD

**Issue by brianmiller** [brianmiller/phvalheim-server#8]
I'm not sure if this is even possible, given OpenID (Steam Auth) requires HTTPS termination.  

We may be able to make a local (internal) only version of PhValheim.  I'm not sure,  we need to test this.

**Comment by Maxver0** [comment]
This would definitely be a useful feature. I've been considering making this server available via a VPN service, such as ZeroTier if it would be possible. Definitely less work to configure the server (no need for SSL, Domain, Port Forwarding, etc.) but it is one extra step for the clients to use ZeroTier alongside it, which ultimately might be easier.

**Comment by brianmiller** [comment]
Solved by #17 

PhValheim >=2.0 no longer requires DNS for client-to-server connections.  However, Steam (PhValheim heavily uses) will always require basic internet access, including the ability to resolve names.  PhValheim downloads steam, mods and games.
